import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Navbar from "./_Components/navbar/page";
import CartContextProvider from "@/context/cartContext";
import SessionProvider from "@/SessionProvider/SessionProvider";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function ClientProviders({ children }: { children: React.ReactNode }) {
  "use client";
  return (
    <SessionProvider>
      <CartContextProvider>
        <Navbar />
        <Toaster position="top-right" richColors />
        {children}
      </CartContextProvider>
    </SessionProvider>
  );
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
